version: '3'

services:
  cassandra:
    image: cassandra:latest
    container_name: myinbox-cassandra
    ports:
      - "9042:9042"


    volumes:
      - data-cassandra:/var/lib/cassandra

volumes:
  data-cassandra:
    driver: local